config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :shows do
      member do
        get :done
        get :start
      end
    end
  end

  root "users#index"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get  "/logout" => "sessions#destroy"

end

app/models/show.rb
class Show < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  # validates (:watched || :watching || :to_watch), presence: true

  # before_save :default_values
  # def default_values
  #   if !self.watched && !self.watching
  #     self.to_watch = true
  #   else
  #     self.watched ||= false
  #     self.watching ||= false
  #     self.to_watch ||= false
  #   end
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :shows
  has_secure_password

  validates :f_name, :l_name, :username, :email_address, :password, :password_confirmation, presence: true, on: :create
  validates_uniqueness_of :username, :email_address, on: :create
  validates :f_name, :l_name, :username, :email_address, presence: true, on: :update

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method(:current_user)

  def authorize
    redirect_to "/login" unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email_address: params[:email_address])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user
    else
      flash.notice = "Incorrect email address and/or password"
      redirect_to("/login")
    end
  end

  def destroy
    session[:user_id] = nil

    flash.notice = "You have successfully logged out!"
    redirect_to("/")
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  include ShowsHelper

  def index
    @user = User.find(params[:user_id])
    @user_shows = @user.shows.order('created_at DESC')
  end

  def new
    @user = User.find(params[:user_id])
    @show = Show.new
  end

  def create
    @user = User.find(params[:user_id])
    @show = Show.new(show_params)
    @show.user_id = params[:user_id]

    if @show.save
      flash.notice = "Saved!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:user_id])
    @show = Show.find(params[:id])
  end

  def edit
    @user = User.find(params[:user_id])
    @show = Show.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @show = Show.find(params[:id])

    if @show.update(show_params)
      flash.notice = "Updated!"
      redirect_to @user
    else
      render template: "shows/edit"
    end
  end

  def destroy
    @show = Show.find(params[:id])
    @show.destroy

    flash.notice = "Deleted!"
    redirect_to :back
  end

  def done
    user = User.find(params[:user_id])
    show = Show.find(params[:id])
    show.watched = true
    show.watching = false
    show.save

    redirect_to :back
  end

  def start
    user = User.find(params[:user_id])
    show = Show.find(params[:id])
    show.to_watch = false
    show.watching = true
    show.save

    redirect_to :back
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      flash.notice = "Account created!"
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end

  end

  def show
    @user = User.find(params[:id])
    @user_shows = @user.shows.order('created_at DESC')
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash.notice = "Account updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil

    flash.notice = "Account deleted!"
    redirect_to "/"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shows_helper.rb
module ShowsHelper

  def show_params
    params.require(:show).permit(
      :title,
      :watched,
      :watching,
      :to_watch,
      :priority,
      :current_episode,
      :current_season,
      :seasons,
      :day_of_week
    )
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def user_params
    params.require(:user).permit(
      :f_name,
      :l_name,
      :username,
      :email_address,
      :password,
      :password_confirmation
    )
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToWatchApp</title>
    <!-- <link rel="icon" type="image/jpg" href="http://emojipop.net/data/images/emoji_set_487.png"> -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="flash"><%= flash.notice %></p>

  <div class="container1">
    <div class="account_info">
      <% if current_user %>
        <%= link_to "@#{current_user.username}", user_path(current_user) %> |
        <%= link_to "Log out", "/logout" %>
      <% else %>
        <%= link_to "Log in", "/login" %> |
        <%= link_to "Create an account", new_user_path %>
      <% end %>
    </div>
  </div>

  <h1 class="app_name">To Watch</h1>
  <div class="content"><%= yield %></div>

</body>
</html>

app/views/shows/_form.html.erb
<% if @show.errors.any? %>
  <div>
    <h4>
      Wait a minute,
      <%= pluralize(@show.errors.count,"error") %>
      here:
    </h4>
    <ol>
      <% @show.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ol>
  </div>
<% end %>

<p>
  <%= f.text_field :title, placeholder: "Title" %>
</p>
<p>
  Have watched
  <%= f.check_box :watched %>
</p>
<p>
  Currently watching
  <%= f.check_box :watching %>
</p>
<p>
  Want to watch:
  <%= f.check_box :to_watch %>
</p>
<p>
  Airs on:
  <%= f.select :day_of_week, [ ['---'], ['Su'], ['M'], ['Tu'], ['W'], ['Th'],
      ['F'], ['Sa'] ] %>
</p>

app/views/shows/edit.html.erb
<h1>Edit show</h1>

<div>
  <%= form_for [ @user, @show ] do |f| %>
    <%= render partial: 'form', locals: {f: f} %>
    <p>
      <%= f.submit "Save" %>
    </p>
  <% end %>
</div>
<p>
  <%= link_to "Cancel", :back %>
</p>

app/views/shows/index.html.erb
<h1><%= "All of @#{@user.username}'s shows" %></h1>

<div>
  <% @user_shows.each do |show| %>
    <p><%= show.title %></p>
    <p><%= link_to "X", user_show_path(@user, show), method: :delete %></p>
  <% end %>
</div>

<!-- <p>
  <%= link_to "Back to all posts", "/", {:class => "back"} %>
</p> -->

app/views/shows/new.html.erb
<h1>Add show</h1>

<div>
  <%= form_for [ @user, @show ] do |f| %>
    <%= render partial: 'form', locals: {f: f} %>
    <p>
      <%= f.submit "Add" %>
    </p>
  <% end %>
</div>
<p>
  <%= link_to "Cancel", :back %>
</p>

app/views/shows/show.html.erb
<div>
  <p><%= link_to "@#{@user.username}", user_path(@user) %></p>
</div>
<div>
  <p><%= @show.title %></p>
</div>
<p>
  <% if @user == current_user %>
    <a>
    <%= link_to "Edit", edit_user_show_path %> |

      <%= link_to "Delete", user_show_path,
          method: :delete,
          data: { confirm: "Are you sure you want to delete this show?" } %>
    </a>
  <% end %>
</p>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div>
    <h4>
      Wait a minute,
      <%= pluralize(@user.errors.count,"error") %>
      here:
    </h4>
    <ol>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ol>
  </div>
<% end %>

<p>
  <%= f.text_field :f_name, placeholder: "First Name" %>
</p>
<p>
  <%= f.text_field :l_name, placeholder: "Last Name" %>
</p>
<p>
  <%= f.text_field :username, placeholder: "Username" %>
</p>
<p>
  <%= f.text_field :email_address, placeholder: "Email Address" %>
</p>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<div>
  <%= form_for @user do |f| %>
    <%= render partial: 'form', locals: {f: f} %>
    <p>
      <%= f.submit "Save" %>
    </p>
  <% end %>
</div>
<p class="back">
  <%= link_to "Cancel", user_path, {:class => "cancel"} %>
</p>

app/views/users/index.html.erb
<h1>All Users<h1>
<ul>
  <% @users.each do |user| %>
    <li><%= user.username %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Create an account<h1>

<div>
  <%= form_for @user do |f| %>
    <%= render partial: 'form', locals: {f: f} %>
    <p>
      <%= f.password_field :password, placeholder: "Password" %>
    </p>
    <p>
      <%= f.password_field :password_confirmation,
                            placeholder: "Password Confirmation" %>
    </p>
    <p>
      <%= f.submit "Create!" %>
    </p>
  <% end %>
</div>
<p class="back">
  <%= link_to "Cancel", "/", {:class => "cancel"} %>
</p>

app/views/users/show.html.erb
<div>
  <% if current_user != @user %>
    <h1><%= "@#{@user.username}" %></h1>
  <% end %>
</div>

<div>
  <nav>
    <div class="nav-watching">Watching</div>
    <div class="nav-to-watch">Want to Watch</div>
    <div class="nav-watched">Watched</div>
    <div class="nav-add-show">
      <%= link_to "+", new_user_show_path(current_user) %>
      <%= link_to "Add show", new_user_show_path(current_user) %>
    <div>
  </nav>

  <div class="list">

    <div class="list-watching">
      <% @user_shows.each do |show| %>
        <% if show.watching %>
          <div class="show-line">
            <p>
              <%= link_to "Done", done_user_show_path(@user, show) %> |
              <%= link_to "Sleep" %>
            </p>
            <p><%= "#{show.title} (#{show.day_of_week})" %></p>
            <p>
              <%= link_to "Edit", edit_user_show_path(@user, show) %> |
              <%= link_to "X", user_show_path(@user, show), method: :delete %>
            </p>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="list-to-watch">
      <% @user_shows.each do |show| %>
        <% if show.to_watch %>
          <div class="show-line">
            <p><%= link_to "Start", start_user_show_path(@user, show) %></p>
            <p><%= show.title %></p>
            <p>
              <%= link_to "Edit", edit_user_show_path(@user, show) %> |
              <%= link_to "X", user_show_path(@user, show), method: :delete %>
            </p>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="list-watched">
      <% @user_shows.each do |show| %>
        <% if show.watched %>
          <div class="show-line">
            <p><%= show.title %></p>
            <p>
              <%= link_to "Edit", edit_user_show_path(@user, show) %> |
              <%= link_to "X", user_show_path(@user, show), method: :delete %>
            </p>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>

</div>

<p>
  <!-- <%= link_to "Back to all posts", "/", {:class => "back"} %> -->
  <% if @user == current_user %>
    <a class="change">
      <%= link_to "Delete Account", user_path(@user),
          method: :delete,
          data: { confirm: "Are you sure you want to permanently delete your account?" } %>
    </a>
  <% end %>
</p>
<div class="edit_prof">
  <% if @user == current_user %>
    <%= link_to "Edit Profile", edit_user_path %>
  <% end %>
</div>